name: Docs

on:
  push: 
    branches: [ master ]
  pull_request: 
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Hexo
      run: npm install --global hexo-cli

    - name: Build website
      run: |
        npm install
        hexo generate

    - name: Clone branch gh-pages
      uses: actions/checkout@v2
      with:
        path: 'gh-pages'
        ref: gh-pages
        submodules: recursive

    - name: Log info
      run: |
        ls ./themes/
        ls ./themes/hipaper/

    - name: Move .git to build
      run: mv './gh-pages/.git' './public'

    - name: Push to pages
      continue-on-error: true
      run: |
        cd './public'
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "Update pages"
        git push
