name: Docs

on:
  push:
    branches:
      - master
      - docs
    paths:
      - '**.yml'
      - '**.toml'
      - '**.md'
      - content/**
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish-doc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.91.2'
        extended: true

    - name: Check out GitHub page repo
      uses: actions/checkout@v3
      with:
        path: 'gh-pages'
        ref: 'gh-pages'

    - name: Build doc artifacts with Hugo
      run: hugo --destination gh-pages --minify

    # TODO: Generate better commit message
    - name: Publish doc artifacts
      continue-on-error: true
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -F- <<-_UBLT_COMMIT_MSG_
        auto: ${{ github.event.head_commit.message }}

        SourceCommit: https://github.com/jcs090218/blog/commit/${{ github.sha }}
        _UBLT_COMMIT_MSG_
        git push
      working-directory: gh-pages
